#!/usr/bin/env bash
# Copy the theme as it currently is on this machine back into files/, so later
# tweaks can be committed. See README.md.
set -euo pipefail

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
FILES="$REPO/files"
MARK_BEGIN="// >>> thunderbird-restyle (managed by install.sh)"
MARK_END="// <<< thunderbird-restyle"
# The markers this repo used before it was renamed, so an older install is
# recognised and replaced instead of being left behind as a duplicate block.
OLD_MARK_BEGIN="// >>> mailspring-modern (managed by install.sh)"
OLD_MARK_END="// <<< mailspring-modern"

if ! PROFILE=$("$REPO/lib/find-profile"); then
  echo "No Thunderbird profile found." >&2
  exit 1
fi
CHROME="$PROFILE/chrome"
echo "Profile: $PROFILE"

# Stylesheets, with the profile path swapped back to the placeholder.
# omarchy-colors.css is generated by the hook, so it isn't kept.
mkdir -p "$FILES/chrome/icons"
for name in userChrome.css userContent.css theme-tokens.css; do
  if [[ -f "$CHROME/$name" ]]; then
    sed "s|$CHROME|@CHROME_DIR@|g" "$CHROME/$name" >"$FILES/chrome/$name"
  fi
done
rm -rf "$FILES/chrome/icons/lucide"
cp -r "$CHROME/icons/lucide" "$FILES/chrome/icons/lucide"

# user.js: the managed block if install.sh wrote one, otherwise the whole file.
USERJS="$PROFILE/user.js"
if grep -qxF "$MARK_BEGIN" "$USERJS" || grep -qxF "$OLD_MARK_BEGIN" "$USERJS"; then
  awk -v b="$MARK_BEGIN" -v e="$MARK_END" -v ob="$OLD_MARK_BEGIN" -v oe="$OLD_MARK_END" '$0 == b { keep = 1; next } $0 == e { keep = 0 } keep' "$USERJS" >"$FILES/user.js"
else
  cp "$USERJS" "$FILES/user.js"
fi

FONT_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/fonts/Inter"
mkdir -p "$FILES/fonts/Inter"
cp "$FONT_DIR"/* "$FILES/fonts/Inter/"

mkdir -p "$FILES/extensions"
if [[ -f "$PROFILE/extensions/sendlater3@kamens.us.xpi" ]]; then
  cp "$PROFILE/extensions/sendlater3@kamens.us.xpi" "$FILES/extensions/"
fi

HOOK="$HOME/.config/omarchy/hooks/theme-set.d/thunderbird-colors"
if [[ -f $HOOK ]]; then
  mkdir -p "$FILES/omarchy"
  cp "$HOOK" "$FILES/omarchy/thunderbird-colors"
fi

# Custom Omarchy themes to carry along (Thunderbird's colours come from the
# current one). Add more names here.
THEMES=(trance)
for name in "${THEMES[@]}"; do
  src="$HOME/.config/omarchy/themes/$name"
  if [[ -d $src ]]; then
    mkdir -p "$FILES/omarchy/themes"
    rm -rf "$FILES/omarchy/themes/$name"
    cp -r "$src" "$FILES/omarchy/themes/$name"
    rm -rf "$FILES/omarchy/themes/$name/.git"
  fi
done

if grep -rlF "$PROFILE" "$FILES" >/dev/null; then
  echo "Warning: these files still contain this machine's profile path:" >&2
  grep -rlF "$PROFILE" "$FILES" >&2
fi

echo "Captured into $FILES"
git -C "$REPO" status --short 2>/dev/null || true
